"""fix cascade delete on user transactions

Revision ID: 5c4fa4d9dd82
Revises: eb49b23d5d42
Create Date: 2026-04-02 00:50:46.588568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4fa4d9dd82'
down_revision: Union[str, Sequence[str], None] = 'eb49b23d5d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
