"""fixing problems

Revision ID: 60fcc495a3e7
Revises: 59715281108e
Create Date: 2026-03-31 21:52:48.707227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fcc495a3e7'
down_revision: Union[str, Sequence[str], None] = '59715281108e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('transactions', 'trans_name')
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='created_at::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('trans_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'name')
    # ### end Alembic commands ###
