"""current_state_after_manual_changes

Revision ID: fb689903598a
Revises: 9e75d1b0e38f
Create Date: 2026-03-31 23:05:39.853476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb689903598a'
down_revision: Union[str, Sequence[str], None] = '9e75d1b0e38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('title', sa.String(length=30), nullable=False))
    op.add_column('transactions', sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'money')
    op.drop_column('transactions', 'title')
    # ### end Alembic commands ###
